=== lazydog-org/persistence-history-parent/history-table/src/main/resources/META-INF/xsd/persistence-history.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns="http://lazydog.org/xml/ns/persistence-history"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://lazydog.org/xml/ns/persistence-history"
    elementFormDefault="qualified">

    <!-- definition of simple elements -->
    <xs:element name="class" type="xs:string"/>
    <xs:element name="column" type="xs:string"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="history-table" type="xs:string"/>
    <xs:element name="history-table-data-source" type="xs:string"/>
    <xs:element name="history-table-suffix" type="xs:string"/>
    <xs:element name="table" type="xs:string"/>
    <xs:element name="table-data-source" type="xs:string"/>

    <!-- definition of complex elements -->
    <xs:element name="attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name">
                    <xs:annotation>
                        <xs:documentation>

                            The attribute name.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="column" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>

                            The table column.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="attribute" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>

                            An attribute for the entity.

                            If no "column" is specified, the "name" will be
                            used to derive the column name.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="entity-mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="class">
                    <xs:annotation>
                        <xs:documentation>

                            The entity class.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="table" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>

                            The table for the entity.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="history-table" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>

                            The history table for the entity.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="attributes" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>

                            The attributes for the entity.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="persistence-history">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="table-data-source">
                    <xs:annotation>
                        <xs:documentation>

                            The table data source.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="history-table-data-source">
                    <xs:annotation>
                        <xs:documentation>

                            The history table data source.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="history-table-suffix" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>

                            The history table suffix.  If no
                            "history-table-suffix" is specified, the default
                            suffix is "_history".

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="entity-mapping" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>

                            The relationship between the entity, table,
                            and history table.

                            If no "table" is specified, the "class" will be
                            used to derive the table name.

                            If no "history-table" is specified, the
                            "class" and "history-table-suffix" will be used to
                            derive the history table name.

                            If no "attributes" is specified, the "class"
                            properties will be used to derive the attributes.
                            
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lazydog-org/persistence-history-parent/history-table/src/test/resources/META-INF/persistence-history.xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence-history
    xmlns="http://lazydog.org/xml/ns/persistence-history"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lazydog.org/xml/ns/persistence-history
                        http://lazydog.org/xml/ns/persistence-history/persistence-history.xsd">

    <table-data-source>jdbc/ComicCollectionPool</table-data-source>
    <history-table-data-source>jdbc/ComicHistoryPool</history-table-data-source>
    <history-table-suffix>_audit</history-table-suffix>
    <entity-mapping>
        <class>org.lazydog.comic.model.Category</class>
    </entity-mapping>
    <entity-mapping>
        <class>org.lazydog.comic.model.Comic</class>
        <table>comic_test</table>
        <history-table>comic_test_history</history-table>
    </entity-mapping>
    <entity-mapping>
        <class>org.lazydog.comic.model.Title</class>
        <table>title_test</table>
        <history-table>title_test_history</history-table>
        <attributes>
            <attribute>
                <name>id</name>
                <column>title_id</column>
            </attribute>
            <attribute>
                <name>name</name>
            </attribute>
        </attributes>
    </entity-mapping>
</persistence-history>
