=== lazydog-org/persistence-history-parent/history-table/src/main/resources/history-table-mappings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns="http://lazydog.org/xml/ns/historytable"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://lazydog.org/xml/ns/historytable"
    elementFormDefault="qualified">

    <!-- definition of simple elements -->
    <xs:element name="entity-class-name" type="xs:string"/>
    <xs:element name="table-data-source" type="xs:string"/>
    <xs:element name="table-name" type="xs:string"/>
    <xs:element name="history-table-data-source" type="xs:string"/>
    <xs:element name="history-table-name" type="xs:string"/>
    
    <!-- definition of attributes -->

    <!-- definition of complex elements -->
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="entity-class-name">
                    <xs:annotation>
                        <xs:documentation>

                            The entity class name.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="table-name" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>

                            The table for the entity class.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="history-table-name" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>

                            The history table for the entity class.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="mappings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="table-data-source">
                    <xs:annotation>
                        <xs:documentation>

                            The table data source.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="history-table-data-source">
                    <xs:annotation>
                        <xs:documentation>

                            The history table data source.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="mapping" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>

                            The relationship between the entity class, table,
                            and history table.

                            If no "table-name" is specified, the
                            "entity-class-name" will be used as the 
                            table name.

                            If no "history-table-name" is specified, the
                            "entity-class-name" with "_history" appended will
                            be used as the history table name.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lazydog-org/persistence-history-parent/history-table/src/test/resources/META-INF/history-table-mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings
    xmlns="http://lazydog.org/xml/ns/historytable"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lazydog.org/xml/ns/historytable
                        http://lazydog.org/xml/ns/historytable/history-table-mappings.xsd">

    <table-data-source>jdbc/Test</table-data-source>
    <history-table-data-source>jdbc/TestHistory</history-table-data-source>
    <mapping>
        <entity-class-name>org.lazydog.test.model.TestEntity1</entity-class-name>
        <table-name>test-entity1</table-name>
        <history-table-name>test-entity1-history</history-table-name>
    </mapping>
    <mapping>
        <entity-class-name>org.lazydog.test.model.TestEntity2</entity-class-name>
    </mapping>
</mappings>
